### ISSUE TITLE
how to solve  the errors

### ISSUE THREAD

**Issue by slackroo** [TimDettmers/bitsandbytes#853] opened 2023-11-02 13:25 UTC
UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
'NoneType' object has no attribute 'cadam32bit_grad_fp32'
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++ BUG REPORT INFORMATION ++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

++++++++++++++++++ /usr/local CUDA PATHS +++++++++++++++++++

+++++++++++++++ WORKING DIRECTORY CUDA PATHS +++++++++++++++
/Users/slackroo/Data_science/LLM/llm_venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda115_nocublaslt.so
/Users/slackroo/Data_science/LLM/llm_venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda111_nocublaslt.so
/Users/slackroo/Data_science/LLM/llm_venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda122_nocublaslt.so
/Users/slackroo/Data_science/LLM/llm_venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda110.so
/Users/slackroo/Data_science/LLM/llm_venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda114.so
/Users/slackroo/Data_science/LLM/llm_venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda120.so
/Users/slackroo/Data_science/LLM/llm_venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda115.so
/Users/slackroo/Data_science/LLM/llm_venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda121.so
/Users/slackroo/Data_science/LLM/llm_venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118_nocublaslt.so
/Users/slackroo/Data_science/LLM/llm_venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda121_nocublaslt.so
/Users/slackroo/Data_science/LLM/llm_venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda111.so
/Users/slackroo/Data_science/LLM/llm_venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda122.so
/Users/slackroo/Data_science/LLM/llm_venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda120_nocublaslt.so
/Users/slackroo/Data_science/LLM/llm_venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so
/Users/slackroo/Data_science/LLM/llm_venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda110_nocublaslt.so
/Users/slackroo/Data_science/LLM/llm_venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda114_nocublaslt.so
/Users/slackroo/Data_science/LLM/llm_venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118.so
/Users/slackroo/Data_science/LLM/llm_venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117_nocublaslt.so

++++++++++++++++++ LD_LIBRARY CUDA PATHS +++++++++++++++++++

++++++++++++++++++++++++++ OTHER +++++++++++++++++++++++++++
COMPILED_WITH_CUDA = False
COMPUTE_CAPABILITIES_PER_GPU = []
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++ DEBUG INFO END ++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Running a quick check that:
    + library is importable
    + CUDA function is callable

WARNING: Please be sure to sanitize sensible info from any such env vars!

Torch not compiled with CUDA enabled

**Comment by turkunov** [comment] 2023-11-02 21:09
Most likely a duplicate of https://github.com/TimDettmers/bitsandbytes/issues/778

**Comment by swumagic** [comment] 2023-11-12 01:42
OR you are  Linux distribution (Ubuntu, MacOS, etc.)system ,AND CUDA Version: 11.X.

Bitsandbytes can support ubuntu.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/TimDettmers/bitsandbytes/releases/download/0.41.0/bitsandbytes-0.41.0-py3-none-any.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）

**Comment by swumagic** [comment] 2023-11-12 01:43
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）

**Closed** 2023-12-29 15:09 UTC

**Comment by rajiv-learner** [comment] 2025-02-27 09:57
I am on Mac M3 .
And I get the same issue . How to resolve it .
I already installed torch with the following command so to have PyTorch  compliant with the Apple Silicon chip.
pip3 install --pre torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/nightly/cpu
