### ISSUE TITLE
Error named symbol not found at line 117 in file /mmfs1/gscratch/zlab/timdettmers/git/bitsandbytes/csrc/ops.cu

### ISSUE THREAD

**Issue by NLP-planet** [TimDettmers/bitsandbytes#568] opened 2023-07-06 10:50 UTC
===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /root/miniconda3/envs/llama-etuning/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so
CUDA exception! Error code: system has unsupported display driver / cuda driver combination
CUDA exception! Error code: initialization error
CUDA SETUP: CUDA runtime path found: /root/miniconda3/envs/llama-etuning/lib/libcudart.so
/root/miniconda3/envs/llama-etuning/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: No GPU detected! Check your CUDA paths. Proceeding to load CPU-only library...
  warn(msg)
CUDA SETUP: Detected CUDA version 118
CUDA SETUP: Loading binary /root/miniconda3/envs/llama-etuning/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so...
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++ BUG REPORT INFORMATION ++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

+++++++++++++++++++ ANACONDA CUDA PATHS ++++++++++++++++++++
/root/miniconda3/envs/llama-etuning/lib/python3.10/site-packages/torch/lib/libc10_cuda.so
/root/miniconda3/envs/llama-etuning/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so
/root/miniconda3/envs/llama-etuning/lib/python3.10/site-packages/torch/lib/libtorch_cuda_linalg.so
/root/miniconda3/envs/llama-etuning/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda110.so
/root/miniconda3/envs/llama-etuning/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda110_nocublaslt.so
/root/miniconda3/envs/llama-etuning/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda111.so
/root/miniconda3/envs/llama-etuning/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda111_nocublaslt.so
/root/miniconda3/envs/llama-etuning/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda112.so
/root/miniconda3/envs/llama-etuning/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda112_nocublaslt.so
/root/miniconda3/envs/llama-etuning/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda113.so
/root/miniconda3/envs/llama-etuning/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda113_nocublaslt.so
/root/miniconda3/envs/llama-etuning/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda114.so
/root/miniconda3/envs/llama-etuning/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda114_nocublaslt.so
/root/miniconda3/envs/llama-etuning/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda115.so
/root/miniconda3/envs/llama-etuning/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda115_nocublaslt.so
/root/miniconda3/envs/llama-etuning/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda116.so
/root/miniconda3/envs/llama-etuning/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda116_nocublaslt.so
/root/miniconda3/envs/llama-etuning/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so
/root/miniconda3/envs/llama-etuning/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117_nocublaslt.so
/root/miniconda3/envs/llama-etuning/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118.so
/root/miniconda3/envs/llama-etuning/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118_nocublaslt.so
/root/miniconda3/envs/llama-etuning/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda120.so
/root/miniconda3/envs/llama-etuning/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda120_nocublaslt.so
/root/miniconda3/envs/llama-etuning/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda121.so
/root/miniconda3/envs/llama-etuning/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda121_nocublaslt.so
/root/miniconda3/envs/llama-etuning/lib/libcudart.so

++++++++++++++++++ /usr/local CUDA PATHS +++++++++++++++++++
/usr/local/cuda-11.8/targets/x86_64-linux/lib/libcudart.so
/usr/local/cuda-11.8/targets/x86_64-linux/lib/stubs/libcuda.so
/usr/local/cuda-11.8/nsight-compute-2022.3.0/target/linux-desktop-glibc_2_11_3-x64/libcuda-injection.so
/usr/local/cuda-11.8/nsight-compute-2022.3.0/target/linux-desktop-t210-a64/libcuda-injection.so
/usr/local/cuda-11.8/nsight-compute-2022.3.0/target/linux-desktop-glibc_2_19_0-ppc64le/libcuda-injection.so

+++++++++++++++ WORKING DIRECTORY CUDA PATHS +++++++++++++++
/root/miniconda3/envs/llama-etuning/lib/python3.10/site-packages/torch/lib/libc10_cuda.so
/root/miniconda3/envs/llama-etuning/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so
/root/miniconda3/envs/llama-etuning/lib/python3.10/site-packages/torch/lib/libtorch_cuda_linalg.so
/root/miniconda3/envs/llama-etuning/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda110.so
/root/miniconda3/envs/llama-etuning/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda110_nocublaslt.so
/root/miniconda3/envs/llama-etuning/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda111.so
/root/miniconda3/envs/llama-etuning/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda111_nocublaslt.so
/root/miniconda3/envs/llama-etuning/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda112.so
/root/miniconda3/envs/llama-etuning/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda112_nocublaslt.so
/root/miniconda3/envs/llama-etuning/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda113.so
/root/miniconda3/envs/llama-etuning/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda113_nocublaslt.so
/root/miniconda3/envs/llama-etuning/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda114.so
/root/miniconda3/envs/llama-etuning/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda114_nocublaslt.so
/root/miniconda3/envs/llama-etuning/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda115.so
/root/miniconda3/envs/llama-etuning/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda115_nocublaslt.so
/root/miniconda3/envs/llama-etuning/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda116.so
/root/miniconda3/envs/llama-etuning/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda116_nocublaslt.so
/root/miniconda3/envs/llama-etuning/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so
/root/miniconda3/envs/llama-etuning/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117_nocublaslt.so
/root/miniconda3/envs/llama-etuning/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118.so
/root/miniconda3/envs/llama-etuning/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118_nocublaslt.so
/root/miniconda3/envs/llama-etuning/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda120.so
/root/miniconda3/envs/llama-etuning/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda120_nocublaslt.so
/root/miniconda3/envs/llama-etuning/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda121.so
/root/miniconda3/envs/llama-etuning/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda121_nocublaslt.so

++++++++++++++++++ LD_LIBRARY CUDA PATHS +++++++++++++++++++
+ /usr/local/cuda-11.8/targets/x86_64-linux/lib CUDA PATHS +
/usr/local/cuda-11.8/targets/x86_64-linux/lib/libcudart.so
/usr/local/cuda-11.8/targets/x86_64-linux/lib/stubs/libcuda.so

++++++++++++++++++++++++++ OTHER +++++++++++++++++++++++++++
COMPILED_WITH_CUDA = True
COMPUTE_CAPABILITIES_PER_GPU = []
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++ DEBUG INFO END ++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Running a quick check that:
    + library is importable
    + CUDA function is callable

WARNING: Please be sure to sanitize sensible info from any such env vars!

Error named symbol not found at line 117 in file /mmfs1/gscratch/zlab/timdettmers/git/bitsandbytes/csrc/ops.cu

**Comment by Daryl149** [comment] 2023-07-07 20:11
See fix: https://github.com/TimDettmers/bitsandbytes/issues/566

**Comment by TimDettmers** [comment] 2023-07-13 19:02
It seems this is a duplicate of #571. It seems you are using a H100 GPU.

**Closed** 2023-07-15 17:25 UTC
Labels: duplicate
