### ISSUE TITLE
`bfloat16` support

### ISSUE THREAD

**Issue by lostmsu** [TimDettmers/bitsandbytes#88] opened 2022-11-04 21:16 UTC
Currently I get

> Gradient+optimizer bit data type combination not supported: grad torch.bfloat16, optimizer torch.uint8

**Comment by TimDettmers** [comment] 2023-01-03 15:00
Thank you! This is an important feature that needs to be implemented. Currently, it's a bit of a mess with all those different CUDA versions and bf support. The problem is that only specific combinations of CUDA + GPUs support bf16, and the library needs to be restructured to be able to be compiled for all of those cases. It causes a bit of a combinatorial explosion in libraries that need to be compiled, which makes it difficult to maintain the library.

If anyone wants to give it a shot, I am happy to work on this if you create a PR.

**Comment by KohakuBlueleaf** [comment] 2023-07-09 04:33
@TimDettmers sorry for bothering you!
Is there any update for this enhancement?
really need bf16 weight + bf16 amp + 8bit optimizer for training some big model...

**Comment by TimDettmers** [comment] 2024-01-07 18:58
Strange, I thought I implemented this. I will check this and update if necessary. Thanks for reporting that it is still not working.

**Comment by TimDettmers** [comment] 2024-01-07 21:54
This has been addressed in 0.39.1 and should work now.

**Closed by TimDettmers** 2024-01-07 21:54 UTC
Labels: bug, enhancement, high priority, Low Risk
