### ISSUE TITLE
Error out of memory at line 351 in file /home/developer/bitsandbytes/csrc/pythonInterface.c SHOULD BE PLENTY VRAM

### ISSUE THREAD

**Issue by phalexo** [TimDettmers/bitsandbytes#464] opened 2023-05-31 21:24 UTC
Problem allocating RAM on host using managed pointers under the Unified Virtual Memory 

and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /home/developer/mambaforge/envs/Guanaco/lib/python3.10/site-packages/bitsandbytes-0.39.0-py3.10.egg/bitsandbytes/libbitsandbytes_cuda118_nocublaslt.so
/home/developer/mambaforge/envs/Guanaco/lib/python3.10/site-packages/bitsandbytes-0.39.0-py3.10.egg/bitsandbytes/cuda_setup/main.py:149: UserWarning: /home/developer/mambaforge/envs/Guanaco did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
/home/developer/mambaforge/envs/Guanaco/lib/python3.10/site-packages/bitsandbytes-0.39.0-py3.10.egg/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/nccl/lib'), PosixPath('/usr/local/lib/openmpi'), PosixPath('/home/developer/anaconda3/lib'), PosixPath('/usr/local/cuda-11.8/lib')}
  warn(msg)
CUDA SETUP: CUDA runtime path found: /usr/local/cuda-11.8/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 5.2
CUDA SETUP: Detected CUDA version 118
/home/developer/mambaforge/envs/Guanaco/lib/python3.10/site-packages/bitsandbytes-0.39.0-py3.10.egg/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: Compute capability < 7.5 detected! Only slow 8-bit matmul is supported for your GPU!
  warn(msg)
CUDA SETUP: Loading binary /home/developer/mambaforge/envs/Guanaco/lib/python3.10/site-packages/bitsandbytes-0.39.0-py3.10.egg/bitsandbytes/libbitsandbytes_cuda118_nocublaslt.so...
loading base model EleutherAI/pythia-12b...
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [01:16<00:00, 25.39s/it]
/home/developer/mambaforge/envs/Guanaco/lib/python3.10/site-packages/peft/utils/other.py:76: FutureWarning: prepare_model_for_int8_training is deprecated and will be removed in a future version. Use prepare_model_for_kbit_training instead.
  warnings.warn(
adding LoRA modules...
trainable params: 188743680 || all params: 12034816000 || trainable: 1.5683137988981302
loaded model
Found cached dataset parquet (/home/developer/.cache/huggingface/datasets/tatsu-lab___parquet/tatsu-lab--alpaca-2b32f0433506ef5f/0.0.0/2a3b91fbd88a2c90d1dbbb32b460cf621d31bd5b05b934492fdef7d8d6f236ec)
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 304.84it/s]
Loading cached processed dataset at /home/developer/.cache/huggingface/datasets/tatsu-lab___parquet/tatsu-lab--alpaca-2b32f0433506ef5f/0.0.0/2a3b91fbd88a2c90d1dbbb32b460cf621d31bd5b05b934492fdef7d8d6f236ec/cache-7688172b91a1f6d4.arrow
Loading cached processed dataset at /home/developer/.cache/huggingface/datasets/tatsu-lab___parquet/tatsu-lab--alpaca-2b32f0433506ef5f/0.0.0/2a3b91fbd88a2c90d1dbbb32b460cf621d31bd5b05b934492fdef7d8d6f236ec/cache-0b873bde6329608e.arrow
torch.float32 705996800 0.058683338085652396
torch.int8 11324620800 0.9413166619143476
  0%|                                                                                                                                          | 0/10000 [00:00<?, ?it/s]
/home/developer/mambaforge/envs/Guanaco/lib/python3.10/site-packages/bitsandbytes-0.39.0-py3.10.egg/bitsandbytes/autograd/_functions.py:318: UserWarning: MatMul8bitLt: inputs will be cast from torch.float32 to float16 during quantization
  warnings.warn(f"MatMul8bitLt: inputs will be cast from {A.dtype} to float16 during quantization")
/home/developer/mambaforge/envs/Guanaco/lib/python3.10/site-packages/transformers/models/gpt_neox/modeling_gpt_neox.py:229: UserWarning: where received a uint8 condition tensor. This behavior is deprecated and will be removed in a future version of PyTorch. Use a boolean condition instead. (Triggered internally at ../aten/src/ATen/native/TensorCompare.cpp:493.)
  attn_scores = torch.where(causal_mask, attn_scores, mask_value)
Error out of memory at line 351 in file /home/developer/bitsandbytes/csrc/pythonInterface.c
/arrow/cpp/src/arrow/filesystem/s3fs.cc:2598:  arrow::fs::FinalizeS3 was not called even though S3 was initialized.  This could lead to a segmentation fault at exit

**Comment by phalexo** [comment] 2023-05-31 21:26
and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /home/developer/mambaforge/envs/Guanaco/lib/python3.10/site-packages/bitsandbytes-0.39.0-py3.10.egg/bitsandbytes/libbitsandbytes_cuda118_nocublaslt.so
/home/developer/mambaforge/envs/Guanaco/lib/python3.10/site-packages/bitsandbytes-0.39.0-py3.10.egg/bitsandbytes/cuda_setup/main.py:149: UserWarning: /home/developer/mambaforge/envs/Guanaco did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
/home/developer/mambaforge/envs/Guanaco/lib/python3.10/site-packages/bitsandbytes-0.39.0-py3.10.egg/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/nccl/lib'), PosixPath('/home/developer/anaconda3/lib'), PosixPath('/usr/local/cuda-11.8/lib'), PosixPath('/usr/local/lib/openmpi')}
  warn(msg)
CUDA SETUP: CUDA runtime path found: /usr/local/cuda-11.8/lib64/libcudart.so.11.0
CUDA SETUP: Highest compute capability among GPUs detected: 5.2
CUDA SETUP: Detected CUDA version 118
/home/developer/mambaforge/envs/Guanaco/lib/python3.10/site-packages/bitsandbytes-0.39.0-py3.10.egg/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: Compute capability < 7.5 detected! Only slow 8-bit matmul is supported for your GPU!
  warn(msg)
CUDA SETUP: Loading binary /home/developer/mambaforge/envs/Guanaco/lib/python3.10/site-packages/bitsandbytes-0.39.0-py3.10.egg/bitsandbytes/libbitsandbytes_cuda118_nocublaslt.so...
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++ BUG REPORT INFORMATION ++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

+++++++++++++++++++ ANACONDA CUDA PATHS ++++++++++++++++++++
/home/developer/mambaforge/envs/Guanaco/lib/python3.10/site-packages/torch/lib/libtorch_cuda_linalg.so
/home/developer/mambaforge/envs/Guanaco/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so
/home/developer/mambaforge/envs/Guanaco/lib/python3.10/site-packages/torch/lib/libc10_cuda.so
/home/developer/mambaforge/envs/Guanaco/lib/python3.10/site-packages/bitsandbytes-0.39.0-py3.10.egg/bitsandbytes/libbitsandbytes_cuda118_nocublaslt.so

++++++++++++++++++ /usr/local CUDA PATHS +++++++++++++++++++
/usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_cuda_linalg.so
/usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_cuda.so
/usr/local/lib/python3.8/dist-packages/torch/lib/libc10_cuda.so
/usr/local/lib/python3.8/dist-packages/torch/lib/libc10d_cuda_test.so
/usr/local/lib/python3.8/dist-packages/torch-1.13.1-py3.8-linux-x86_64.egg/torch/lib/libtorch_cuda_linalg.so
/usr/local/lib/python3.8/dist-packages/torch-1.13.1-py3.8-linux-x86_64.egg/torch/lib/libtorch_cuda.so
/usr/local/lib/python3.8/dist-packages/torch-1.13.1-py3.8-linux-x86_64.egg/torch/lib/libc10_cuda.so
/usr/local/lib/python3.8/dist-packages/torch-1.13.1-py3.8-linux-x86_64.egg/torch/lib/libtorch_cuda_cu.so
/usr/local/lib/python3.8/dist-packages/torch-1.13.1-py3.8-linux-x86_64.egg/torch/lib/libtorch_cuda_cpp.so
/usr/local/cuda-11.8/targets/x86_64-linux/lib/stubs/libcuda.so
/usr/local/cuda-11.8/targets/x86_64-linux/lib/libcudart.so
/usr/local/cuda-11.8/compat/libcuda.so
/usr/local/cuda-11.8/nsight-compute-2022.3.0/target/linux-desktop-glibc_2_11_3-x64/libcuda-injection.so
/usr/local/cuda-11.8/nsight-compute-2022.3.0/target/linux-desktop-glibc_2_19_0-ppc64le/libcuda-injection.so
/usr/local/cuda-11.8/nsight-compute-2022.3.0/target/linux-desktop-t210-a64/libcuda-injection.so

+++++++++++++++ WORKING DIRECTORY CUDA PATHS +++++++++++++++


++++++++++++++++++ LD_LIBRARY CUDA PATHS +++++++++++++++++++
++++ /usr/local/cuda-11.8/extras/CUPTI/lib64 CUDA PATHS ++++

++++++++++++++++ /usr/local/lib CUDA PATHS +++++++++++++++++
/usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_cuda_linalg.so
/usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_cuda.so
/usr/local/lib/python3.8/dist-packages/torch/lib/libc10_cuda.so
/usr/local/lib/python3.8/dist-packages/torch/lib/libc10d_cuda_test.so
/usr/local/lib/python3.8/dist-packages/torch-1.13.1-py3.8-linux-x86_64.egg/torch/lib/libtorch_cuda_linalg.so
/usr/local/lib/python3.8/dist-packages/torch-1.13.1-py3.8-linux-x86_64.egg/torch/lib/libtorch_cuda.so
/usr/local/lib/python3.8/dist-packages/torch-1.13.1-py3.8-linux-x86_64.egg/torch/lib/libc10_cuda.so
/usr/local/lib/python3.8/dist-packages/torch-1.13.1-py3.8-linux-x86_64.egg/torch/lib/libtorch_cuda_cu.so
/usr/local/lib/python3.8/dist-packages/torch-1.13.1-py3.8-linux-x86_64.egg/torch/lib/libtorch_cuda_cpp.so
++++++++++ /usr/local/cuda-11.8/lib64 CUDA PATHS +++++++++++

+++++++++++ /usr/lib/x86_64-linux-gnu CUDA PATHS +++++++++++
/usr/lib/x86_64-linux-gnu/libcuda.so
/usr/lib/x86_64-linux-gnu/libicudata.so

++++++++++++++++++++++++++ OTHER +++++++++++++++++++++++++++
COMPILED_WITH_CUDA = True
COMPUTE_CAPABILITIES_PER_GPU = ['5.2', '5.2', '5.2', '5.2']
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++ DEBUG INFO END ++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Running a quick check that:
    + library is importable
    + CUDA function is callable


WARNING: Please be sure to sanitize sensible info from any such env vars!

SUCCESS!
Installation was successful!

**Comment by mathekcbo** [comment] 2023-06-02 06:36
I have the same issue. maybe helpful or not - my observation: the warmup seems to start for maybe 10 seconds. so the GPU (mine RTX3090) runs at 100% using maybe 40% of VRAM (7b modell) before suddenly everything stops as @phalexo mentions.
Planty of RAM and VRAM free.

**Comment by TimDettmers** [comment] 2023-07-16 02:36
This is a duplicate of #477. Please find my response there and continue the discussion in that issue. Higher memory usage is expected on Windows.

**Closed by TimDettmers** 2023-07-16 02:36 UTC
Labels: duplicate
