### ISSUE TITLE
Anything but plain "greedy" search "not implemented for 'Half'"

### ISSUE THREAD

**Issue by auwsom** [TimDettmers/bitsandbytes#59] opened 2022-10-10 02:27 UTC
I posted this issue to GH/HF/transformers, but it probably belongs here.
https://github.com/huggingface/transformers/issues/19445 (same title)

Also, this may help. This Eleuther model is able to use sampling with int8 optimization. They actually refer to Load_in_8bit saying it has superceded their solution, but it doesnt do sampling.
"superceded bloom int8 optimized model doesnt do sampling"
https://huggingface.co/hivemind/gpt-j-6B-8bit/discussions/8
https://huggingface.co/hivemind/gpt-j-6B-8bit

Thanks Tim!

**Comment by younesbelkada** [comment] 2022-10-12 07:07
Hey!

Closing as it is a duplicate of https://github.com/huggingface/transformers/issues/19445

**Closed** 2022-10-12 08:23 UTC

**Comment by auwsom** [comment] 2022-10-13 04:58
@younesbelkada  seems to be working with the Bloom model locally without the inputids workaround.
