### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by haimai96** [TimDettmers/bitsandbytes#916] opened 2023-12-15 08:37 UTC
![image](https://github.com/TimDettmers/bitsandbytes/assets/127096815/7a82bf97-f2e7-48d5-946a-dbfbd52d86b9)

**ERROR:**
bin E:\model_collect\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda116.dll
Loading checkpoint shards:   0%|          | 0/2 [00:20<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    m = AutoModelForCausalLM.from_pretrained(
  File "E:\model_collect\venv\lib\site-packages\transformers\models\auto\auto_factory.py", line 566, in from_pretrained
    return model_class.from_pretrained(
  File "E:\model_collect\venv\lib\site-packages\transformers\modeling_utils.py", line 3694, in from_pretrained
    ) = cls._load_pretrained_model(
  File "E:\model_collect\venv\lib\site-packages\transformers\modeling_utils.py", line 4104, in _load_pretrained_model
    new_error_msgs, offload_index, state_dict_index = _load_state_dict_into_meta_model(
  File "E:\model_collect\venv\lib\site-packages\transformers\modeling_utils.py", line 786, in _load_state_dict_into_meta_model
    set_module_quantized_tensor_to_device(
  File "E:\model_collect\venv\lib\site-packages\transformers\integrations\bitsandbytes.py", line 96, in set_module_quantized_tensor_to_device
    new_value = bnb.nn.Int8Params(new_value, requires_grad=False, **kwargs).to(device)
  File "E:\model_collect\venv\lib\site-packages\bitsandbytes\nn\modules.py", line 333, in to
    return self.cuda(device)
  File "E:\model_collect\venv\lib\site-packages\bitsandbytes\nn\modules.py", line 297, in cuda
    CB, CBt, SCB, SCBt, coo_tensorB = bnb.functional.double_quant(B)
  File "E:\model_collect\venv\lib\site-packages\bitsandbytes\functional.py", line 2012, in double_quant
    out_row = torch.zeros(A.shape, device=device, dtype=torch.int8)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 44.00 MiB (GPU 0; 4.00 GiB total capacity; 3.35 GiB already allocated; 0 bytes free; 3.47 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by Titus-von-Koeller** [comment] 2023-12-15 12:27
@haimai96 Please provide more info why you think this is related to the BNB library. This looks like a simple OOM, what would happen if you load a model that doesn't fit your memory.

I'll close this without further background info explaining your point. Please be as specific as you can be.

**Comment by younesbelkada** [comment] 2023-12-18 13:31
Also, this seems related to HF transformers, I propose to close the issue and @haimai96 if you can post an issue on transformers https://github.com/huggingface/transformers/issues with a clean reproducer that would be great!

**Closed by younesbelkada** 2023-12-18 13:31 UTC
Labels: likely not a BNB issue, waiting for info, proposing to close

**Comment by haimai96** [comment] 2023-12-25 04:28
@younesbelkada @Titus-von-Koeller I run on a windows environment, and my card information is as follows:
![image](https://github.com/TimDettmers/bitsandbytes/assets/127096815/12149124-d2cc-4c2c-a517-da4510c5e951)
![image](https://github.com/TimDettmers/bitsandbytes/assets/127096815/cf8e00b0-f02c-4bd3-ada7-295d30655cd3)
![image](https://github.com/TimDettmers/bitsandbytes/assets/127096815/872bf3ee-706f-439f-acd6-c0981f40bd43)
