### ISSUE TITLE
RuntimeError: expected scalar type Half but found Float

### ISSUE THREAD

**Issue by NapalmCandy** [TimDettmers/bitsandbytes#103] opened 2022-12-04 15:53 UTC
I am trying dreambooth on Automatic1111, I see that do not reach the 10Gb vRAM of my RTX 3080.

It is a bug or I am doing something wrong?

```
Starting Dreambooth training...
 VRAM cleared.
 Allocated: 0.0GB
 Reserved: 3.3GB

 Loaded model.
 Allocated: 0.0GB
 Reserved: 0.0GB

The config attributes {'timestep_values': None} were passed to DDPMScheduler, but are not expected and will be ignored. Please verify your scheduler_config.json configuration file.
 Scheduler Loaded
 Allocated: 0.4GB
 Reserved: 0.4GB

  Total target lifetime optimization steps = 3000
 CPU: False Adam: True, Prec: fp16, Prior: True, Grad: True, TextTr: False
 Allocated: 3.6GB
 Reserved: 3.7GB

Steps:   0%|                                                                                  | 0/3000 [00:00<?, ?it/s]Error completing request
Arguments: ('Norav1', 'C:\\Users\\Napal\\Pictures\\Entrenamiento_IA\\Nora_y_Greta\\Por_separado\\512\\Nora\\selecto\\png', 'C:\\Users\\Napal\\Pictures\\Entrenamiento_IA\\regularizacion\\girl', 'noritigr', '*', '', '', 1.0, 7.5, 40.0, 300, 512, False, False, 1, 1, 1, 3000, 1, True, 5e-06, False, 'constant', 0, True, 0.9, 0.999, 0.01, 1e-08, 1, 0, 0, 'fp16', True, '', False, True, True) {}
Traceback (most recent call last):
  File "E:\Auto1111\modules\call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "E:\Auto1111\modules\call_queue.py", line 28, in f
    res = func(*args, **kwargs)
  File "E:\Auto1111\extensions\sd_dreambooth_extension\dreambooth\dreambooth.py", line 265, in start_training
    trained_steps = main(config)
  File "E:\Auto1111\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 769, in main
    encoder_hidden_states = text_encoder(batch["input_ids"])[0]
  File "E:\Auto1111\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\Auto1111\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 722, in forward
    return self.text_model(
  File "E:\Auto1111\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\Auto1111\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 643, in forward
    encoder_outputs = self.encoder(
  File "E:\Auto1111\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\Auto1111\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 574, in forward
    layer_outputs = encoder_layer(
  File "E:\Auto1111\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\Auto1111\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 317, in forward
    hidden_states, attn_weights = self.self_attn(
  File "E:\Auto1111\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\Auto1111\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 257, in forward
    attn_output = torch.bmm(attn_probs, value_states)
RuntimeError: expected scalar type Half but found Float

Steps:   0%|                                                                                  | 0/3000 [00:00<?, ?it/s]
```

**Comment by TimDettmers** [comment] 2023-02-02 20:24
This does not look like a bitsandbytes problem. I think the problem is that you have the model or the input in the wrong precision. Both the inputs to the model and the model itself need to have the same precision.

I close this since it is not related to bitsandbytes.

**Closed by TimDettmers** 2023-02-02 20:24 UTC
Labels: invalid

**Comment by ipoletaev** [comment] 2023-05-04 01:11
I actually think it is related to the `StableEmbedding` class behavior, that under hood uses fp32 normalization which is casted by outer amp context to other precision and hence the error.
