### ISSUE TITLE
AttributeError: libbitsandbytes_cpu.so: undefined symbol: cget_col_row_stats

### ISSUE THREAD

**Issue by tanzzilaalam** [TimDettmers/bitsandbytes#357] opened 2023-04-30 17:59 UTC
The error is coming repeatedly. Error message: 

File "/home/tanzila/DISK/finix/dev/language_model/.venv/lib/python3.9/site-packages/transformers/modeling_utils.py", line 2803, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/home/tanzila/DISK/finix/dev/language_model/.venv/lib/python3.9/site-packages/transformers/modeling_utils.py", line 3144, in _load_pretrained_model
    new_error_msgs, offload_index, state_dict_index = _load_state_dict_into_meta_model(
  File "/home/tanzila/DISK/finix/dev/language_model/.venv/lib/python3.9/site-packages/transformers/modeling_utils.py", line 710, in _load_state_dict_into_meta_model
    set_module_8bit_tensor_to_device(
  File "/home/tanzila/DISK/finix/dev/language_model/.venv/lib/python3.9/site-packages/transformers/utils/bitsandbytes.py", line 78, in set_module_8bit_tensor_to_device
    new_value = bnb.nn.Int8Params(new_value, requires_grad=False, has_fp16_weights=has_fp16_weights).to(device)
  File "/home/tanzila/DISK/finix/dev/language_model/.venv/lib/python3.9/site-packages/bitsandbytes/nn/modules.py", line 227, in to
    return self.cuda(device)
  File "/home/tanzila/DISK/finix/dev/language_model/.venv/lib/python3.9/site-packages/bitsandbytes/nn/modules.py", line 191, in cuda
    CB, CBt, SCB, SCBt, coo_tensorB = bnb.functional.double_quant(B)
  File "/home/tanzila/DISK/finix/dev/language_model/.venv/lib/python3.9/site-packages/bitsandbytes/functional.py", line 1642, in double_quant
    row_stats, col_stats, nnz_row_ptr = get_colrow_absmax(
  File "/home/tanzila/DISK/finix/dev/language_model/.venv/lib/python3.9/site-packages/bitsandbytes/functional.py", line 1531, in get_colrow_absmax
    lib.cget_col_row_stats(ptrA, ptrRowStats, ptrColStats, ptrNnzrows, ct.c_float(threshold), rows, cols)
  File "/home/tanzila/anaconda3/envs/venv/lib/python3.9/ctypes/__init__.py", line 395, in __getattr__
    func = self.__getitem__(name)
  File "/home/tanzila/anaconda3/envs/venv/lib/python3.9/ctypes/__init__.py", line 400, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /home/tanzila/DISK/finix/dev/language_model/.venv/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cget_col_row_stats

these are the dependencies: 30 April, 2023

accelerate
appdirs
bitsandbytes==0.38.1
git+https://github.com/huggingface/peft.git
git+https://github.com/huggingface/transformers.git
sentencepiece
sentence_transformers
gradio
torch==1.13.0

**Comment by dacorvo** [comment] 2023-06-08 09:53
This looks like a duplicate of #156

**Closed** 2023-12-30 15:11 UTC
