### ISSUE TITLE
non-existent path throwing Error invalid device ordinal

### ISSUE THREAD

**Issue by uccollab** [TimDettmers/bitsandbytes#470] opened 2023-06-01 16:04 UTC
Hello, I'm trying to run the following [HuggingFace notebook](https://colab.research.google.com/drive/1VoYNfYDKcKRQRor98Zbf2-9VQTtGJ24k?usp=sharing#scrollTo=ym9bmcpKP9XT
).
The code runs fine on Colab, but when trying it (with no changes) on my system (Windows 11, WSL2, NVidia Quadro RTX 5000 16GB) I get the following error upon starting the training loop (trainer.train()):

```
You're using a GPTNeoXTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
/home/uccollab/support-text-gen/lib/python3.9/site-packages/transformers/models/gpt_neox/modeling_gpt_neox.py:230: UserWarning: where received a uint8 condition tensor. This behavior is deprecated and will be removed in a future version of PyTorch. Use a boolean condition instead. (Triggered internally at ../aten/src/ATen/native/TensorCompare.cpp:493.)
  attn_scores = torch.where(causal_mask, attn_scores, mask_value)
Error invalid device ordinal at line 359 in file /home/tim/git/bitsandbytes/csrc/pythonInterface.c
```

I've seen that this is potentially fixable by editing pythonInterface.c, according to [this other thread](https://github.com/stoperro/bitsandbytes_windows/commit/e02f078000ed19fe57321c464dd16d60f18d6803)

The problem is the specified path "/home/tim/git/bitsandbytes/csrc/pythonInterface.c", there's no such path on my WSL installation (also "tim" is not my username). I have no clue where bitesandbytes is getting that file from and a search doesn't return anything as well. I also tried compiling from source but the issue persists.

**Comment by mathekcbo** [comment] 2023-06-01 18:42
But I still wonder if it is just a parameter that needs to be set somewhere ...

**Comment by uccollab** [comment] 2023-06-01 19:15
> i faced the same issue. I dont think the path is the point, as after source recompile the issue just changes the path prefix.
> 
> There may seems to be a fix [commit](https://github.com/TimDettmers/bitsandbytes/commit/13116a4bc2f0a95a73bbc72bcfecce6a09528a62)
> 
> But this fix didnt work for me, as I now get the error (with a 7b model and an RTX3090):
> 
> `Error out of memory at line 351 in file /home/.../bitsandbytes/csrc/pythonInterface.c `
> 
> But it may work for you.

Did you, by any chance, try reducing batch size etc. to reduce memory footprint? Or perhaps doing some gradient accumulation?

**Comment by jllllll** [comment] 2023-06-01 20:17
> > i faced the same issue. I dont think the path is the point, as after source recompile the issue just changes the path prefix.
> > There may seems to be a fix [commit](https://github.com/TimDettmers/bitsandbytes/commit/13116a4bc2f0a95a73bbc72bcfecce6a09528a62)
> > But this fix didnt work for me, as I now get the error (with a 7b model and an RTX3090):
> > `Error out of memory at line 351 in file /home/.../bitsandbytes/csrc/pythonInterface.c `
> > But it may work for you.
> 
> Also do you have any idea why I get a completely non-existent path on my end? I can't even try this fix.

The path is referencing the source code at compile time, so it is a path on Tim's system not yours.

**Comment by phalexo** [comment] 2023-06-01 20:28
> > > i faced the same issue. I dont think the path is the point, as after source recompile the issue just changes the path prefix.
> > > There may seems to be a fix [commit](https://github.com/TimDettmers/bitsandbytes/commit/13116a4bc2f0a95a73bbc72bcfecce6a09528a62)
> > > But this fix didnt work for me, as I now get the error (with a 7b model and an RTX3090):
> > > `Error out of memory at line 351 in file /home/.../bitsandbytes/csrc/pythonInterface.c `
> > > But it may work for you.
> > 
> > 
> > Also do you have any idea why I get a completely non-existent path on my end? I can't even try this fix.
> 
> The path is referencing the source code at compile time, so it is a path on Tim's system not yours.

lol, you have to download the stuff from github of course.

**Comment by mathekcbo** [comment] 2023-06-02 05:31
@phalexo thank you, i´ll test. 

@jllllll I really think, the path thing is a bug in logging that is not really a thing. I am not an expert on c or python. But if at 99% of all installations everything seems ok, then I would assume that the real issue is something different.

**Comment by mathekcbo** [comment] 2023-06-02 05:35
@jllllll 
If you want to test the code change i mentioned. There is an easy guide, I followed. Go to YT and search the channel AemonAlgiz. The vid from yesterday regarding peft shows how to compile from source - if that helps.

**Comment by peter-ch** [comment] 2023-06-02 11:58
I have the same problem. When can I expect this to be fixed? It breaks my work and I can't do anything about it.

**Comment by phalexo** [comment] 2023-06-02 17:53
Well, at least I have figured out the build process for pyarrow and bitsandbytes, that makes certain that changes take effect for qlora training. 

Although problems themselves remain. Would have to figure out Nvidia UVM memory allocation and AWS S3 file system to fix the actual problems.

**Comment by phalexo** [comment] 2023-06-02 21:13
> i faced the same issue. I dont think the path is the point, as after source recompile the issue just changes the path prefix.
> 
> There may seems to be a fix [commit](https://github.com/TimDettmers/bitsandbytes/commit/13116a4bc2f0a95a73bbc72bcfecce6a09528a62)
> 
> But this fix didnt work for me, as I now get the error (with a 7b model and an RTX3090):
> 
> `Error out of memory at line 351 in file /home/.../bitsandbytes/csrc/pythonInterface.c `
> 
> But it may work for you.

What architecture GPU do you have? Is below sm_60?

**Comment by phalexo** [comment] 2023-06-03 11:10
> @phalexo thank you, i´ll test.
> 
> @jllllll I really think, the path thing is a bug in logging that is not really a thing. I am not an expert on c or python. But if at 99% of all installations everything seems ok, then I would assume that the real issue is something different.

        void *cget_managed_ptr(size_t bytes)
        {
                void *ptr;
                //CUDA_CHECK_RETURN(cudaMallocManaged(&ptr, bytes, cudaMemAttachHost));
                //CUDA_CHECK_RETURN(cudaMallocManaged(&ptr, bytes));
                CUDA_CHECK_RETURN(cudaMallocHost(&ptr, bytes));

                CUDA_CHECK_RETURN(cudaPeekAtLastError());

                return ptr;
        }

**Comment by mathekcbo** [comment] 2023-06-03 14:44
> > i faced the same issue. I dont think the path is the point, as after source recompile the issue just changes the path prefix.
> > There may seems to be a fix [commit](https://github.com/TimDettmers/bitsandbytes/commit/13116a4bc2f0a95a73bbc72bcfecce6a09528a62)
> > But this fix didnt work for me, as I now get the error (with a 7b model and an RTX3090):
> > `Error out of memory at line 351 in file /home/.../bitsandbytes/csrc/pythonInterface.c `
> > But it may work for you.
> 
> What architecture GPU do you have? Is it below sm_60?

I have no clue, but while compiling bab again, i saw some output - it seems to say sm_75

**Comment by mathekcbo** [comment] 2023-06-03 14:51
> > @phalexo thank you, i´ll test.
> > @jllllll I really think, the path thing is a bug in logging that is not really a thing. I am not an expert on c or python. But if at 99% of all installations everything seems ok, then I would assume that the real issue is something different.
> 
> ```
>     void *cget_managed_ptr(size_t bytes)
>     {
>             void *ptr;
>             //CUDA_CHECK_RETURN(cudaMallocManaged(&ptr, bytes, cudaMemAttachHost));
>             //CUDA_CHECK_RETURN(cudaMallocManaged(&ptr, bytes));
>             CUDA_CHECK_RETURN(cudaMallocHost(&ptr, bytes));
> 
>             CUDA_CHECK_RETURN(cudaPeekAtLastError());
> 
>             return ptr;
>     }
> ```

I tried your change - didnt work. I try qlora - maybe it is a little too fresh and therefore in a sense unstable.

my current output (after patching):

`(qlora) mathe@DESKTOP-TFD1T29:~/og2/qlora/qlora2$ python qlora.py     --model_name_or_path huggyllama/llama-7b     --output_dir ./output/guanaco-7b     --logging_steps 10     --save_strategy steps     --data_seed 42     --save_steps 500     --save_total_limit 40     --evaluation_strategy steps     --eval_dataset_size 10     --max_eval_samples 2      --per_device_eval_batch_size 1     --max_new_tokens 32     --dataloader_num_workers 1     --group_by_length     --logging_strategy steps     --remove_unused_columns False     --do_train     --do_eval     --do_mmlu_eval     --lora_r 64     --lora_alpha 16     --lora_modules all     --double_quant     --quant_type nf4     --bf16     --bits 4     --warmup_ratio 0.03     --lr_scheduler_type constant     --gradient_checkpointing     --dataset oasst1     --source_max_len 16     --target_max_len 512     --per_device_train_batch_size 1     --gradient_accumulation_steps 16     --max_steps 16     --eval_steps 2     --learning_rate 0.0002     --adam_beta2 0.999     --max_grad_norm 0.3     --lora_dropout 0.1     --weight_decay 0.0     --seed 0

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /home/mathe/miniconda3/envs/qlora/lib/python3.10/site-packages/bitsandbytes-0.39.0-py3.10.egg/bitsandbytes/libbitsandbytes_cuda117.so
/home/mathe/miniconda3/envs/qlora/lib/python3.10/site-packages/bitsandbytes-0.39.0-py3.10.egg/bitsandbytes/cuda_setup/main.py:149: UserWarning: /home/mathe/miniconda3/envs/qlora did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
/home/mathe/miniconda3/envs/qlora/lib/python3.10/site-packages/bitsandbytes-0.39.0-py3.10.egg/bitsandbytes/cuda_setup/main.py:149: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/usr/local/cuda/lib64/libcudart.so.11.0'), PosixPath('/usr/local/cuda/lib64/libcudart.so')}.. We'll flip a coin and try one of these, in order to fail forward.
Either way, this might cause trouble in the future:
If you get `CUDA error: invalid device function` errors, the above might be the cause and the solution is to make sure only one ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] in the paths that we search based on your env.
  warn(msg)
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so.11.0
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 117
CUDA SETUP: Loading binary /home/mathe/miniconda3/envs/qlora/lib/python3.10/site-packages/bitsandbytes-0.39.0-py3.10.egg/bitsandbytes/libbitsandbytes_cuda117.so...
loading base model huggyllama/llama-7b...
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:09<00:00,  4.96s/it]
adding LoRA modules...
trainable params: 79953920.0 || all params: 3660320768 || trainable: 2.184341894267557
loaded model
Adding special tokens.
Found cached dataset json (/home/mathe/.cache/huggingface/datasets/timdettmers___json/timdettmers--openassistant-guanaco-c93588435bc90172/0.0.0/e347ab1c932092252e717ff3f949105a4dd28b27e842dd53157d2f72e276c2e4)
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 651.09it/s]
Loading cached processed dataset at /home/mathe/.cache/huggingface/datasets/timdettmers___json/timdettmers--openassistant-guanaco-c93588435bc90172/0.0.0/e347ab1c932092252e717ff3f949105a4dd28b27e842dd53157d2f72e276c2e4/cache-d991ce8f1e1c3330.arrow
Loading cached processed dataset at /home/mathe/.cache/huggingface/datasets/timdettmers___json/timdettmers--openassistant-guanaco-c93588435bc90172/0.0.0/e347ab1c932092252e717ff3f949105a4dd28b27e842dd53157d2f72e276c2e4/cache-6b0cf5fb3c32afe1.arrow
Splitting train dataset in train and validation according to `eval_dataset_size`
Loading cached split indices for dataset at /home/mathe/.cache/huggingface/datasets/timdettmers___json/timdettmers--openassistant-guanaco-c93588435bc90172/0.0.0/e347ab1c932092252e717ff3f949105a4dd28b27e842dd53157d2f72e276c2e4/cache-2e22dd8adbe76462.arrow and /home/mathe/.cache/huggingface/datasets/timdettmers___json/timdettmers--openassistant-guanaco-c93588435bc90172/0.0.0/e347ab1c932092252e717ff3f949105a4dd28b27e842dd53157d2f72e276c2e4/cache-49649f7b8eb98ede.arrow
Loading cached processed dataset at /home/mathe/.cache/huggingface/datasets/timdettmers___json/timdettmers--openassistant-guanaco-c93588435bc90172/0.0.0/e347ab1c932092252e717ff3f949105a4dd28b27e842dd53157d2f72e276c2e4/cache-d080629d36617e88.arrow
Loading cached processed dataset at /home/mathe/.cache/huggingface/datasets/timdettmers___json/timdettmers--openassistant-guanaco-c93588435bc90172/0.0.0/e347ab1c932092252e717ff3f949105a4dd28b27e842dd53157d2f72e276c2e4/cache-9e2a175e246f5402.arrow
Found cached dataset json (/home/mathe/.cache/huggingface/datasets/json/default-fc41f0ba3c3f2704/0.0.0/e347ab1c932092252e717ff3f949105a4dd28b27e842dd53157d2f72e276c2e4)
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 665.13it/s]
torch.bfloat16 422060032 0.1153065849032323
torch.uint8 3238002688 0.8846206784649213
torch.float32 266240 7.273663184633547e-05
  0%|                                                                                                                              | 0/16 [00:00<?, ?it/s]Error out of memory at line 353 in file /home/mathe/og2/qlora/bitsandbytes/csrc/pythonInterface.c
/arrow/cpp/src/arrow/filesystem/s3fs.cc:2598:  arrow::fs::FinalizeS3 was not called even though S3 was initialized.  This could lead to a segmentation fault at exit`

**Comment by phalexo** [comment] 2023-06-03 15:08
Two different problems. 

For this problem you have to rebuild arrow and pyarrow, which is a bit more involved. 

The only solution I have at the moment for the latter problem is ugly.

  void Finalize(bool from_destructor = false) {
    bool expected = true;
    is_finalized_.store(true);
    if (is_initialized_.compare_exchange_strong(expected, false)) {
      if (from_destructor) {
        ARROW_LOG(WARNING)
            << " arrow::fs::FinalizeS3 was not called even though S3 was initialized.  "
               "This could lead to a segmentation fault at exit (hope not)";
        RegionResolver::ResetDefaultInstance();
        //Aws::ShutdownAPI(aws_options_);
      }
    }
  }

**Comment by phalexo** [comment] 2023-06-03 15:29
> > > i faced the same issue. I dont think the path is the point, as after source recompile the issue just changes the path prefix.
> > > There may seems to be a fix [commit](https://github.com/TimDettmers/bitsandbytes/commit/13116a4bc2f0a95a73bbc72bcfecce6a09528a62)
> > > But this fix didnt work for me, as I now get the error (with a 7b model and an RTX3090):
> > > `Error out of memory at line 351 in file /home/.../bitsandbytes/csrc/pythonInterface.c `
> > > But it may work for you.
> > 
> > 
> > What architecture GPU do you have? Is it below sm_60?
> 
> I have no clue, but while compiling bab again, i saw some output - it seems to say sm_75

It compiles for multiple architectures, so you may see several of them. Nvidia UVM has different level hardware support for UVM below sm_60 and above sm_60.

**Comment by mathekcbo** [comment] 2023-06-04 08:00
> 

ok, it seems to be 86 i guess

> Ampere (CUDA 11.1 and later)
> SM80 or SM_80, compute_80 –
> NVIDIA [A100](https://amzn.to/3GqeDrq) (the name “Tesla” has been dropped – GA100), NVIDIA DGX-A100
> **SM86 or SM_86, compute_86** – (from [CUDA 11.1 onwards](https://docs.nvidia.com/cuda/ptx-compiler-api/index.html))
> Tesla GA10x cards, RTX Ampere – RTX 3080, **GA102 – RTX 3090**,

**Comment by mathekcbo** [comment] 2023-06-04 08:04
@phalexo 
I did a proper recompile as you mentioned.
Thanks for trying, your help and your time! - i will wait for further developement and try my stuff on colab in the meanwhile.

**Comment by RickyWang111** [comment] 2023-06-24 11:55
> @phalexo I did a proper recompile as you mentioned.正如你提到的，我做了一个适当的重新编译。 Thanks for trying, your help and your time! - i will wait for further developement and try my stuff on colab in the meanwhile.感谢您的尝试，您的帮助和您的时间！- 我将等待进一步的开发，同时在Colab上尝试我的东西。

Could you tell me if you solve this problem? I have the same problem.

**Comment by AlecJamesCook** [comment] 2023-06-29 15:44
Did anyone find a fix for this? I am having the same problem

**Comment by mathekcbo** [comment] 2023-06-29 16:59
I tried latest version 0.39,1 with and without changes as mentioned above, but didnt got it working. I only found everything working as is using  colab :(

**Comment by TimDettmers** [comment] 2023-07-16 02:33
This is a two-fold problem. One is that the `cudaMemPrefetchAsync` function is not supported on Windows. The other is that the granularity for allocation managed memory on  Windows is 64kb (see here for more information: https://stackoverflow.com/questions/60269623/cuda-unified-memory-and-windows-10).

This means, on windows, this feature does not work well for small optimizer states. Currently, all optimizers with less than 20000 kb are ignored by bitsandbytes. 

On second thought, this is likely not the problem. The problem can be that Windows allows only for allocation of relatively small amounts of page-locked memory, that is memory where it can be ensured that the memory addresses of the pages remain the same.  What this means is that the only solution might be to buy more CPU RAM, or use less paged optimizer states. 

While I do not officially support Windows, this seems to be a blocking issue. I will try to find a workaround for the pythonInteract.c issue and try to add functionality to exclude tensors of a certain size from paged memory. This should help with the out-of-memory issue.

**Comment by jllllll** [comment] 2023-07-16 02:41
@TimDettmers https://github.com/stoperro/bitsandbytes_windows/commit/e02f078000ed19fe57321c464dd16d60f18d6803

**Comment by TimDettmers** [comment] 2023-07-17 04:10
This looks actually like a perfect fix. Let me add that.

**Comment by TimDettmers** [comment] 2023-07-17 05:13
This has been fixed and pushed to pip. Memory problems might remain, but these are Windows-specific and there is nothing I can do about that. Thank you @jllllll and everyone involved, this was an important bugfix.

**Closed by TimDettmers** 2023-07-17 05:13 UTC
Labels: enhancement, high priority
