### ISSUE TITLE
Please tag version 0.39.0

### ISSUE THREAD

**Issue by ccoulombe** [TimDettmers/bitsandbytes#484] opened 2023-06-05 21:03 UTC
Hello, 

version 0.39.0 is on PyPI but no tag/release exists for it in the repo. Can you please tag the relevant commit with the version?
I believe that would be 0f40fa3

Thanks

**Comment by TimDettmers** [comment] 2023-07-16 02:10
The problem is version 0.39.0 had major issues with 8-bit serialization, which were only discovered later and fixed in 0.39.1. 

I want to discourage people from using that version, but I can understand that having a tag for this would make it easy to help support it for all use cases that do not involve 8-bit serialization. 

Any ideas on what we could do here to provide a tag but also make people aware it has major errors?

**Comment by ccoulombe** [comment] 2023-07-17 20:58
I believe at the time of this issue there was not a newer release (0.39.1) but only commits on the main branch. Hence this issue.
The solution is to release a newer version, which has been done! :) 

That said, I can see value in tagging 0.39.0 and especially in documenting the major issue in its release notes. This could help users and support staff in not using that and finding about it.

But users will try newer versions.

**Closed** 2023-12-29 15:13 UTC
Labels: documentation, enhancement, high priority
