### ISSUE TITLE
CUDA setup

### ISSUE THREAD

**Issue by amrakm** [TimDettmers/bitsandbytes#95] opened 2022-11-15 09:58 UTC
I got this error when tried to run dreambooth:

```Python
>>> import torch
>>> torch.cuda.is_available()
True
>>> print(torch.cuda.current_device())
0
>>> print(torch._C._cuda_getCompiledVersion(), 'cuda compiled version')
11070 cuda compiled version
>>> import bitsandbytes
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/amrakm/anaconda3/envs/dreambooth/lib/python3.9/site-packages/bitsandbytes/__init__.py", line 6, in <module>
    from .autograd._functions import (
  File "/home/amrakm/anaconda3/envs/dreambooth/lib/python3.9/site-packages/bitsandbytes/autograd/_functions.py", line 5, in <module>
    import bitsandbytes.functional as F
  File "/home/amrakm/anaconda3/envs/dreambooth/lib/python3.9/site-packages/bitsandbytes/functional.py", line 13, in <module>
    from .cextension import COMPILED_WITH_CUDA, lib
  File "/home/amrakm/anaconda3/envs/dreambooth/lib/python3.9/site-packages/bitsandbytes/cextension.py", line 113, in <module>
    lib = CUDASetup.get_instance().lib
  File "/home/amrakm/anaconda3/envs/dreambooth/lib/python3.9/site-packages/bitsandbytes/cextension.py", line 109, in get_instance
    cls._instance.initialize()
  File "/home/amrakm/anaconda3/envs/dreambooth/lib/python3.9/site-packages/bitsandbytes/cextension.py", line 59, in initialize
    binary_name, cudart_path, cuda, cc, cuda_version_string = evaluate_cuda_setup()
  File "/home/amrakm/anaconda3/envs/dreambooth/lib/python3.9/site-packages/bitsandbytes/cuda_setup/main.py", line 125, in evaluate_cuda_setup
    cuda_version_string = get_cuda_version(cuda, cudart_path)
  File "/home/amrakm/anaconda3/envs/dreambooth/lib/python3.9/site-packages/bitsandbytes/cuda_setup/main.py", line 45, in get_cuda_version
    check_cuda_result(cuda, cudart.cudaRuntimeGetVersion(ctypes.byref(version)))
  File "/home/amrakm/anaconda3/envs/dreambooth/lib/python3.9/ctypes/__init__.py", line 395, in __getattr__
    func = self.__getitem__(name)
  File "/home/amrakm/anaconda3/envs/dreambooth/lib/python3.9/ctypes/__init__.py", line 400, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: python: undefined symbol: cudaRuntimeGetVersion
>>> 
```

CUDA seems to be installed and pytorch is able to see it

```
nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Thu_Nov_18_09:45:30_PST_2021
Cuda compilation tools, release 11.5, V11.5.119
Build cuda_11.5.r11.5/compiler.30672275_0
```

**Comment by omerarshad** [comment] 2022-11-18 20:39
any update on this? Facing same issue

**Comment by amrakm** [comment] 2022-11-20 13:54
I think it was related to CUDA environment PATH. I re installed CUDA and followed the instruction [here](https://www.tensorflow.org/install/pip) 

but then got a different error

**Comment by meanna** [comment] 2022-12-24 02:36
See: https://github.com/huggingface/diffusers/issues/1207#issuecomment-1364444031

What works for me (cuda 11.6, Python 3.9) is

- !pip install torch
- install packages requires by LLM.int8()
  - !pip install --quiet bitsandbytes
  - !pip install --quiet git+https://github.com/huggingface/transformers.git # Install latest version of transformers
  - !pip install --quiet accelerate
  - !pip install --quiet sentencepiece
- !conda install -y cudatoolkit
- check the path of libcudart.so
  - !find /opt/conda/ -name libcudart.so
    - /opt/conda/lib/libcudart.so
    - /opt/conda/pkgs/cudatoolkit-11.3.1-h2bc3f7f_2/lib/libcudart.so
- The problem is bitsandbytes can not find libcudart.so, so we have to set
  - ```
    import os
    os.environ['LD_LIBRARY_PATH'] = '/opt/conda/lib/'
    ```
Using export LD_LIBRARY_PATH='/opt/conda/lib/' may not work in some settings.

**Comment by StatsGary** [comment] 2022-12-28 14:11
I am still getting this issue: 
`CUDA Setup failed despite GPU being available. Inspect the CUDA SETUP outputs aboveto fix your environment!
        If you cannot find any issues and suspect a bug, please open an issue with detals about your environment:
        https://github.com/TimDettmers/bitsandbytes/issues`

I tried the steps to resolve this, but it still seems an issue: 

`
git clone git@github.com:TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=1
python setup.py install
`

Anyone else with the same issue? When I try `nvidia-smi` I know my GPU is being detected and works well with PyTorch.

**Comment by StatsGary** [comment] 2022-12-28 16:08
> See: [huggingface/diffusers#1207 (comment)](https://github.com/huggingface/diffusers/issues/1207#issuecomment-1364444031)
> 
> What works for me (cuda 11.6, Python 3.9) is
> 
> * !pip install torch
> * install packages requires by LLM.int8()
>   
>   * !pip install --quiet bitsandbytes
>   * !pip install --quiet git+https://github.com/huggingface/transformers.git # Install latest version of transformers
>   * !pip install --quiet accelerate
>   * !pip install --quiet sentencepiece
> * !conda install -y cudatoolkit
> * check the path of libcudart.so
>   
>   * !find /opt/conda/ -name libcudart.so
>     
>     * /opt/conda/lib/libcudart.so
>     * /opt/conda/pkgs/cudatoolkit-11.3.1-h2bc3f7f_2/lib/libcudart.so
> * The problem is bitsandbytes can not find libcudart.so, so we have to set
>   
>   * ```
>     import os
>     os.environ['LD_LIBRARY_PATH'] = '/opt/conda/lib/'
>     ```
> 
> Using export LD_LIBRARY_PATH='/opt/conda/lib/' may not work in some settings.

This didn't work in my case.

**Comment by StatsGary** [comment] 2023-01-09 13:03
My issue was resolved by conflicting CUDA toolkits. I removed the installed CUDA toolkit, as my venv came shipped with Cuda runtime alongside PyTorch. As soon as I did this, everything worked.

**Comment by TimDettmers** [comment] 2023-02-02 18:35
Thanks for reporting this error! I have seen this before and it is usually caused, just as @StatsGary says, by having multiple CUDA versions installed. As such, this is not a bug, but the documentation / CUDA SETUP output could be improved to help people debug what is going on.

Please for all others let me know if you still cannot resolve this issue by removing conflicting CUDA versions.

**Comment by huangwei2913** [comment] 2023-08-16 01:36
I have already configured $LD_LIBRARY_PATH huangwei@huangwei:~$ echo $LD_LIBRARY_PATH
:/usr/local/cuda-11.4/lib64:/usr/local/cuda-11.4/extras/CUPTI/lib64:/usr/local/cuda-11.4/lib64:/usr/local/cuda-11.4/extras/CUPTI/lib64, however, the bitsanbytes still cannot find the cuda setup, what is wrong?

**Comment by milinddeore** [comment] 2023-09-19 10:27
Check your cuda version for torch and torchvision, because bitsandbytes compile with `CUDA_VERSION=117` (when i am writing this comment). 

Run, `pip list` and check the torch cuda version.
to make compatible torch version. 

Either compile bitsandbytes with given CUDA_VERSION 
```
git clone https://github.com/TimDettmers/bitsandbytes
cd bitsandbytes
CUDA_VERSION=117 make cuda11x
python setup.py install
```
OR
```
pip install torch==2.0.1+cu117 torchvision==0.15.2+cu117 -f https://download.pytorch.org/whl/torch_stable.html
```

**Comment by Battlebands** [comment] 2023-11-18 03:19
Hi everyone im new on this could any explain to me in a More detailed way how you pip install or yo remover the cuda toookit im trying my best to understand but cant, sorry for the inconvenient

**Comment by OnePawProductions** [comment] 2023-11-19 23:45
Hi, I'm also new, and very inexperienced. Would someone be willing to handhold me through this process? I've been doing stable diffusion on the webui for a few  months now, but downloading Dreambooth has completely wrecked my program. It won't even boot now, and removing the Dreambooth folder from extensions didn't fix it. 

I am inexperienced to the level of:

-what is a CUDA?
- how does one "run" something? What is a pip?
- what is torch and torchvision?
- how does one git clone?
- what are these things in the steps to do, what programs do you do them in, and how?

I have a very basic self taught knowledge of a bit of Javascript, CSS, and kinda a passing familiarity with Python. But I am not familiar with computer jargon and programming to this extend. Ie, I can google solutions, but I find myself unable to parse the jargon into actionable steps. 

I'm fairly certain I'm lacking the familiarity with computer things to even understand what it is that I don't understand. I don't even know where to start or how to find the path to figuring out how to ask the right questions.

Would someone be willing to babysit me through solving this issue? The only thing I can think of is to back up my models, extensions, and config.json and config-ui.json files and then just...uninstall/reinstall.

**Comment by OnePawProductions** [comment] 2023-11-20 05:53
Hello again,

I eventually got my tech savvy friend to check it out, and he couldn't make heads or tails either.

In case anyone else has this problem and suddenly finds their A1111 unable to boot because of the Dreambooth Extension, try this (it is uninstall/reinstall, unfortunately):

-grab all of your "my stuff" files. This could be models, textual inversion files, yaml files, txt files, config files for the ui, theme files
-remember to grab embeddings, and to save your extensions, especially if you've altered them or created your own
-if your outputs are auto-saved INSIDE the webui program files, grab the ones you care about

Save those all to a different folder

Uninstall, reinstall, update, and you may need to also reinstall and update pytorch as well. Next don't put the old extension files back into the extensions folder immediately, instead 
 first re-download the extensions using the webui itself.  There are other, associated files that get created that are necessary for them to function, that aren't in the extensions folder. 

Once downloaded, go to your saved backups of your extensions, and pull out the "guts" of the extension files and replace them with the "guts" of your "my stuff" files. They should be as you remember.

Lastly, as far as I can tell there are dependencies other than A111 that are necessary to run the Dreambooth extension. I think they are something about Linux, and something about CUDA, which has something to do with...your graphics card?

I got into this with a background in the arts, and I'm learning as I go. Just spent a VERY frustrating 10 hours doing all of this. I hope I might spare someone else the trouble.

Next, I shall look into Google Colab for Dreambooth, instead. Revisit installing direct to the webui once I smarten up some about coding and things. Cheers!

**Comment by yuren892** [comment] 2023-11-22 08:44
Another tech-savvy individual saved, simply by removing the Dreambooth extension!

Thanks, OnePawProductions

**Closed** 2023-12-29 15:16 UTC
Labels: documentation, enhancement
